name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.mcunnin38 }}
          password: ${{ secrets.Ddckr_pat_ZI2i-ecD_t45mTRQisqpTTApTAU }}
    
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: Lab3Mcunnin/
          push: true
          tags: mcunnin38/Lab3Mcunnin:${{github.run_number}}